name: Integration continue et déploiement de notre site de présentation du SIAO

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
    
jobs:
  lint:
    name: Vérification du code HTML/CSS
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Initialiser le projet Node
      run: npm init -y
    - name: Installer les dépendances stylelint/htmlhint
      run: |
        npm install --save-dev stylelint stylelint-config-standard htmlhint

    - name: Lint HTML
      run: npx htmlhint "**/*.html"

    - name: Lint CSS
      run: npx stylelint "**/*.css"

  deploy:
    name: Déploiement GitHub Pages
    needs: lint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Préparer les fichiers à publier
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Déployer vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
